In [10]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt

In [11]:
data=pd.read_csv("/kaggle/input/train-csv/train.csv")
data.head()

label  pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  \
0      1       0       0       0       0       0       0       0       0   
1      0       0       0       0       0       0       0       0       0   
2      1       0       0       0       0       0       0       0       0   
3      4       0       0       0       0       0       0       0       0   
4      0       0       0       0       0       0       0       0       0   

   pixel8  ...  pixel774  pixel775  pixel776  pixel777  pixel778  pixel779  \
0       0  ...         0         0         0         0         0         0   
1       0  ...         0         0         0         0         0         0   
2       0  ...         0         0         0         0         0         0   
3       0  ...         0         0         0         0         0         0   
4       0  ...         0         0         0         0         0         0   

   pixel780  pixel781  pixel782  pixel783  
0         0         0         0         0  
1         0         0         0         0  
2         0         0         0         0  
3         0         0         0         0  
4         0         0         0         0  

[5 rows x 785 columns]

In [12]:
data=np.array(data)
m, n=data.shape
np.random.shuffle(data)

data_dev=data[0:1000].T
Y_dev=data_dev[0]
X_dev=data_dev[1:n]
X_dev=X_dev/255.

data_train=data[1000:m].T
Y_train=data_train[0]
X_train=data_train[1:n]
X_train=X_train/255.
_,m_train=X_train.shape

In [13]:
Y_train


array([8, 9, 3, ..., 4, 5, 8])

In [14]:
def init_params():
    W1=np.random.rand(10,784)-0.5
    b1=np.random.rand(10,1)-0.5
    W2=np.random.rand(10,10)-0.5
    b2=np.random.rand(10,1)-0.5
    return W1,b1,W2,b2
def ReLU(Z):
    return np.maximum(Z,0)
def softmax(Z):
    return np.exp(Z)/sum(np.exp(Z))
     #A=np.exp(Z)/np.sum(np.exp(Z))
 
    
def forward_prop(W1,b1,W2,b2,X):
    Z1=W1.dot(X)+b1
    A1=ReLU(Z1)
    Z2=W2.dot(A1)+b2
    A2=softmax(Z2)
    return Z1,A1,Z2,A2
def ReLU_deriv(Z):
    return Z>0
def one_hot(Y):
    one_hot_Y=np.zeros((Y.size, Y.max()+1))
    one_hot_Y[np.arange(Y.size),Y]=1
    one_hot_Y=one_hot_Y.T
    return one_hot_Y
def backward_prop(Z1, A1, Z2, A2, W1, W2, X, Y):
    one_hot_Y = one_hot(Y)
    dZ2 = A2 - one_hot_Y
    dW2 = 1 / m * dZ2.dot(A1.T)
    db2 = 1 / m * np.sum(dZ2)
    dZ1 = W2.T.dot(dZ2) * ReLU_deriv(Z1)
    dW1 = 1 / m * dZ1.dot(X.T)
    db1 = 1 / m * np.sum(dZ1)
    return dW1, db1, dW2, db2
def update_params(W1,b1,W2,b2,dW1,db1,dW2,db2,alpha):
    W1=W1-alpha*dW1
    b1=b1-alpha*db1 #np.reshape(db1,(10,1))
    W2=W2-alpha*dW2
    b2=b2-alpha*db2 #np.reshape(db2,(10,1))
    return W1,b1,W2,b2


In [15]:
def loss(X,Y,A2):
    m=Y.size
    log_likelihood=-np.log(A2[range(m)])
    loss=1/m*np.sum(log_likelihood)
    return loss
def get_predictions(A2):
    return np.argmax(A2,0)
def get_accuracy(predictions, Y):
    print(predictions, Y)
    return np.sum(predictions==Y)/Y.size
def gradient_descent(X,Y,alpha,iterations):
    W1,b1,W2,b2=init_params()
    for i in range(iterations):
        Z1,A1,Z2,A2=forward_prop(W1,b1,W2,b2,X)
        dW1,db1,dW2,db2=backward_prop(Z1,A1,Z2,A2,W1,W2,X,Y) #(Z1,A1,Z2,A2,W2,X,Y)
        W1,b1,W2,b2=update_params(W1,b1,W2,b2,dW1,db1,dW2,db2,alpha)
        if i % 5==0:
            print("iteration:",i)
            predictions=get_predictions(A2)
            print(get_accuracy(predictions,Y))       
    return W1,b1,W2,b2
    loss()

In [16]:
W1, b1, W2, b2= gradient_descent(X_train, Y_train, 0.10, 500)

iteration: 0
[7 6 8 ... 8 7 8] [8 9 3 ... 4 5 8]
0.08648780487804877
iteration: 5
[7 6 3 ... 9 9 3] [8 9 3 ... 4 5 8]
0.15890243902439025
iteration: 10
[7 9 0 ... 9 1 3] [8 9 3 ... 4 5 8]
0.20729268292682926
iteration: 15
[7 9 0 ... 9 1 3] [8 9 3 ... 4 5 8]
0.26709756097560977
iteration: 20
[7 9 0 ... 9 1 3] [8 9 3 ... 4 5 8]
0.3311707317073171
iteration: 25
[7 9 0 ... 9 1 3] [8 9 3 ... 4 5 8]
0.37641463414634146
iteration: 30
[7 9 0 ... 9 1 3] [8 9 3 ... 4 5 8]
0.4139512195121951
iteration: 35
[7 9 0 ... 9 1 3] [8 9 3 ... 4 5 8]
0.4455121951219512


KeyboardInterrupt: 

In [ ]:
def make_predictions(X, W1, b1, W2, b2):
    _, _, _, A2 = forward_prop(W1, b1, W2, b2, X)
    predictions = get_predictions(A2)
    return predictions

def test_prediction(index, W1, b1, W2, b2):
    current_image = X_train[:, index, None]
    prediction = make_predictions(X_train[:, index, None], W1, b1, W2, b2)
    label = Y_train[index]
    print("Prediction: ", prediction)
    print("Label: ", label)
    
    current_image = current_image.reshape((28, 28)) * 255
    plt.gray()
    plt.imshow(current_image, interpolation='nearest')
    plt.show()

In [ ]:
test_prediction(0, W1, b1, W2, b2)
test_prediction(1, W1, b1, W2, b2)
test_prediction(2, W1, b1, W2, b2)
test_prediction(3, W1, b1, W2, b2)
test_prediction(4, W1, b1, W2, b2)


In [ ]:
test_prediction(5, W1, b1, W2, b2)
test_prediction(6, W1, b1, W2, b2)
test_prediction(7, W1, b1, W2, b2)
test_prediction(8, W1, b1, W2, b2)
test_prediction(9, W1, b1, W2, b2)